apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest
  namespace: argocd # Namespace where your Argo CD application is defined
spec:
  destination:
    namespace: everest-system # Target namespace for Everest components within the cluster
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: everest
    targetRevision: 1.6.0 # Or HEAD for the latest version of the chart
    helm:
      parameters:
      - name: server.service.type
        value: "LoadBalancer"  # Exposes the main Everest UI service externally via a load balancer
      - name: upgrade.preflightChecks
        value: "false"  # Disables preflight upgrade checks for smoother updates
      - name: dbNamespace.enabled
        value: "false"  # Prevents creation of a separate namespace for the database (as everest-db handles operators)
      # PMM Configuration Parameters
      - name: pmm.enabled
        value: "true" # Enables the deployment of Percona Monitoring and Management (PMM) components
      - name: pmm.service.type
        value: "LoadBalancer" # Exposes the PMM service externally via a load balancer
      # If you have an external PMM server, you would configure its details here.
      # Otherwise, the chart will attempt to deploy a PMM server within your cluster.
      # - name: pmm.server.url
      #   value: "https://your-external-pmm-server-ip"
      # - name: pmm.server.username
      #   value: "admin"
      # - name: pmm.server.password
      #   value: "your-pmm-password"
  syncPolicy:
    automated:
      prune: false  # Prevents deletion of critical resources during sync
      selfHeal: true  # Ensures ArgoCD automatically fixes any drifted configurations
    syncOptions:
    - CreateNamespace=true  # Automatically creates namespaces if they do not exist
    - RespectIgnoreDifferences=true  # Ignores changes in certain Kubernetes objects to avoid unwanted updates
    - ServerSideApply=true  # Enables server-side apply to prevent sync issues with Custom Resource Definitions (CRDs)
  ignoreDifferences:
  # The JWT key is randomly generated if `server.jwtKey` is not set.
  # This prevents ArgoCD from marking it as out-of-sync on each sync.
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: everest-jwt
    namespace: everest-system
  # If `server.initialAdminPassword` is not set, the chart generates a random password.
  # This prevents ArgoCD from marking the Secret as out-of-sync.
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: everest-accounts
    namespace: everest-system
  # If OLM (Operator Lifecycle Manager) is deployed without cert-manager,
  # the below TLS certificates are randomly generated. This prevents sync issues.
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: packageserver-service-cert
    namespace: everest-olm
  # APIService CA bundles and annotations are automatically updated.
  # Ignoring differences prevents unnecessary sync failures.
  - group: apiregistration.k8s.io
    jqPathExpressions:
    - .spec.caBundle
    - .metadata.annotations
    kind: APIService
    name: v1.packages.operators.coreos.com