apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest-db
  namespace: argocd
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: everest-db-namespace
    targetRevision: 1.6.0
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
