apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest
  namespace: argocd
spec:
  destination:
    namespace: everest
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: everest
    targetRevision: 1.6.0
    helm:
      parameters:
      - name: upgrade.preflightChecks
        value: "false"
      - name: dbNamespace.enabled
        value: "false"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: everest-jwt
    namespace: everest-system
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: everest-accounts
    namespace: everest-system
