apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest
  namespace: argocd
spec:
  destination:
    namespace: everest
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    chart: everest
    targetRevision: 1.6.0
    helm:
      valueFiles:
      - values-everest.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
