apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest-db
  namespace: argocd
spec:
  destination:
    namespace: everest-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/dbazhenov/argocd-public.git
    path: configs/
    targetRevision: main
    helm:
      chart: everest-db-namespace
      repoURL: https://percona.github.io/percona-helm-charts/
      targetRevision: 1.6.0
