apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.6.0
    chart: everest-db-namespace
    helm:
      values: |
        # Configuration for the MongoDB Operator
        mongodb:
          enabled: true # Set to true to enable the MongoDB Operator installation
          installPlanApproval: Automatic # Automatically approve OLM InstallPlan for this operator
          # The following values are for a MongoDB database instance.
          # Since you only want the operator, these can be commented out or removed.
          # If you set enabled: false above, these would be ignored anyway.
          # size: 1
          # databaseType: "psmdb"
          # psmdb:
          #   crVersion: "1.16.0"
          #   image: "percona/percona-server-mongodb:6.0.12-10"
          #   allowUnsafeConfigurations: true
          #   replsets:
          #     - name: rs0
          #       size: 1
          #       volumeSpec:
          #         persistentVolumeClaim:
          #           resources:
          #             requests:
          #               storage: 2Gi
        # Configuration for the PostgreSQL Operator
        postgresql:
          enabled: true # Set to true to enable the PostgreSQL Operator installation
          installPlanApproval: Automatic # Automatically approve OLM InstallPlan for this operator
          # Add any PostgreSQL-specific values here if needed for the operator itself,
          # or if you plan to enable instance creation directly via this chart later.
        # Configuration for the XtraDB Cluster Operator
        pxc:
          enabled: true # Set to true to enable the XtraDB Cluster Operator installation
          installPlanApproval: Automatic # Automatically approve OLM InstallPlan for this operator
          # Add any XtraDB-specific values here if needed for the operator itself,
          # or if you plan to enable instance creation directly via this chart later.
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
