apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: everest-db
  namespace: argocd
spec:
  destination:
    namespace: everest
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: everest-db-namespace
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.6.0
  syncPolicy:
    automated:
      prune: true  # Automatically removes outdated resources no longer present in the desired state
      selfHeal: true  # Detects and corrects drift by enforcing the expected resource state
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
